version: '3.5'

networks:
  bramlettny:

services:
  rabbitmq:
    image: rabbitmq:3.6-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      bramlettny:
        aliases:
          - rabbitmq

  db:
    image: "postgres:11"
    container_name: "my_postgres"
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      bramlettny:
        aliases:
          - redis

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  elastic:
    image: amazon/opendistro-for-elasticsearch:0.9.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    networks:
      bramlettny:
        aliases:
          - elastic

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test-topic:5:2"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    build:
      dockerfile: Dockerfile
      context: nginx/
    ports:
      - "9000:9000"
    networks:
      bramlettny:
        aliases:
          - nginx
  server:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "1323:1323"
    networks:
      bramlettny:
        aliases:
          - server
  web:
    build:
      dockerfile: Dockerfile
      context: web/
    ports:
      - "3000:3000"
    networks:
      bramlettny:
        aliases:
          - web


